server:
  port: 8091
  contextPath: /delegate

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PORTAL_RTU
    password: PORTAL_RTU
    driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org.springframework.web.servlet.mvc.method: DEBUG
    org.springframework.web: ERROR
    com.baxter: DEBUG
  file: logs/NH-PMA-PACRestService-Service.log